### PR TITLE
Feature/new architecture

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by NikAtSpark — CHANGES_REQUESTED** [review]
It has a set of conflicts, otherwise, it looks good

**Comment by DanAtSpark** [comment]
> It has a set of conflicts, otherwise, it looks good

@NikAtSpark they should be resolved by now

**Comment by DanAtSpark** [comment]
> It has a set of conflicts, otherwise, it looks good

@NikAtSpark they should be resolved by now

**Comment by ghost** [comment]
@NikAtSpark All merge conflicts were resolved

**Review by NikAtSpark — APPROVED** [review]

**Pull request merged**
